# Generated by Django 5.2.1 on 2025-11-06 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_question_is_closed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
