# Generated by Django 5.2.1 on 2025-11-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_groupproxy_userproxy_remove_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('employee', 'Сотрудник'), ('manager', 'Начальник отдела'), ('sector_manager', 'Начальник сектора'), ('director', 'Генеральный директор')], default='employee', max_length=20, verbose_name='Роль'),
        ),
    ]
