# Generated by Django 5.2.1 on 2025-11-06 07:51

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projecttimer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activeproject',
            options={'verbose_name': 'Активный проект', 'verbose_name_plural': 'Активные проекты'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='projecttimer',
            options={'verbose_name': 'Таймер проекта', 'verbose_name_plural': 'Таймеры проектов'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterField(
            model_name='activeproject',
            name='in_work',
            field=models.BooleanField(default=False, verbose_name='Запущен'),
        ),
        migrations.AlterField(
            model_name='activeproject',
            name='last_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время запуска'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_time',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Общее время'),
        ),
        migrations.AlterField(
            model_name='projecttimer',
            name='in_work',
            field=models.BooleanField(default=False, verbose_name='Запущен'),
        ),
        migrations.AlterField(
            model_name='projecttimer',
            name='last_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время запуска'),
        ),
        migrations.AlterField(
            model_name='projecttimer',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timers', to='projects.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='projecttimer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_timers', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project', verbose_name='Проект'),
        ),
        migrations.AddConstraint(
            model_name='projecttimer',
            constraint=models.UniqueConstraint(fields=('user', 'project'), name='uniq_user_project_timer'),
        ),
    ]
