# Generated by Django 5.2.1 on 2025-11-07 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_activeproject_options_alter_project_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='artifacts',
            field=models.TextField(blank=True, verbose_name='Артефакты'),
        ),
        migrations.AddField(
            model_name='task',
            name='review_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий проверки'),
        ),
        migrations.AddField(
            model_name='task',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки'),
        ),
        migrations.AddField(
            model_name='task',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Проверил'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('in_review', 'На проверке'), ('done', 'Готово')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='task_attachments/%Y/%m/%d/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Вложение задачи',
                'verbose_name_plural': 'Вложения задач',
            },
        ),
    ]
