# Generated by Django 5.2.1 on 2025-11-09 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_timeentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='artifacts',
        ),
        migrations.RemoveField(
            model_name='task',
            name='review_comment',
        ),
        migrations.RemoveField(
            model_name='task',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='reviewed_by',
        ),
        migrations.AddField(
            model_name='project',
            name='review_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий проверки проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='review_status',
            field=models.CharField(choices=[('none', 'Не на проверке'), ('in_review', 'На проверке'), ('approved', 'Принят'), ('rejected', 'Возвращен')], default='none', max_length=20, verbose_name='Статус проверки'),
        ),
        migrations.AddField(
            model_name='project',
            name='review_submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда отправлен на проверку'),
        ),
        migrations.AddField(
            model_name='project',
            name='review_submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_projects_for_review', to=settings.AUTH_USER_MODEL, verbose_name='Кто отправил на проверку'),
        ),
        migrations.AddField(
            model_name='project',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Проверил проект'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('done', 'Готово')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
