# Generated by Django 5.2.1 on 2025-11-09 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_task_completed_at_alter_task_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttimer',
            name='current_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='running_timers', to='projects.task', verbose_name='Текущая задача'),
        ),
        migrations.AlterField(
            model_name='projecttimer',
            name='in_work',
            field=models.BooleanField(default=False, verbose_name='Идёт отсчёт'),
        ),
    ]
